/**
 * The optional default stylesheet, generated for a prefix.
 *
 * **The requirement it is written against: it must style the HTML emitter's
 * output untouched.** A saved report from `handle.emit('html')` and the
 * virtualized view are the same diff and must not look like two products, and
 * spec 13.3 makes them the same cursor, so making them the same stylesheet costs
 * one file and buys the guarantee. Everything the view needs beyond what the
 * emitter writes is expressed as a `data-` attribute, so every selector below
 * either applies to both documents or is qualified by an attribute only one of
 * them carries.
 *
 * It is a function of the prefix rather than a static file because the prefix is
 * configurable per component, per spec 13.0, and a consumer who changes it would
 * otherwise have to hand write the whole sheet. `styles/*.css` in this package
 * are this function's output for the default prefix, generated by
 * `scripts-and-commands/gen_stylesheet.mjs` and checked in the gate, so the file
 * a bundler imports and the string this returns cannot drift.
 *
 * Two decisions worth defending:
 *
 *   1. **`white-space: pre-wrap` on the cell class.** The emitter writes a cell's
 *      newline through unchanged and does not invent a `<br>`, which is right:
 *      inventing markup for data is how a report starts lying about its input. So
 *      the decision about what a newline looks like belongs here, in the
 *      stylesheet, and this is it. Without it a multiline CSV field collapses to
 *      one line and the diff appears to show a change that is not there.
 *
 *   2. **Colour is never the only signal.** Spec 8.5 calls this a correctness
 *      issue for colour blind reviewers rather than a nicety. The view renders a
 *      real marker cell; the emitter has no such element, so for its documents
 *      the same glyph comes from generated content on the row number gutter. The
 *      two are mutually exclusive by selector so no document gets both.
 */

import { assertClassPrefix, DEFAULT_CLASS_PREFIX } from './classes.ts';

export interface StylesheetOptions {
  prefix?: string;
  /** Emit the `:root` custom property defaults. Off gives structure only, for a
   *  consumer who supplies the whole palette from their own design tokens. */
  variables?: boolean;
}

/**
 * The light palette of spec 8.3, extended with the tokens the emitter's classes
 * need that section 8.3 predates: `moved`, `finding` and `suppressed`.
 */
export const LIGHT_VARIABLES: Readonly<Record<string, string>> = {
  'font-family': 'system-ui, sans-serif',
  'font-size': '13px',
  'font-mono': 'ui-monospace, SFMono-Regular, Menlo, monospace',
  'row-height': '28px',
  'cell-padding-x': '8px',
  'border-color': '#e2e2e2',
  'header-bg': '#fafafa',
  'body-bg': '#ffffff',
  'body-fg': '#1a1a1a',
  'added-bg': '#e8f5e9',
  'added-fg': '#1b5e20',
  'deleted-bg': '#ffebee',
  'deleted-fg': '#b71c1c',
  'modified-bg': '#fff8e1',
  'modified-fg': '#6d4c00',
  'moved-bg': '#eef3fb',
  'finding-bg': '#fdeaea',
  'finding-fg': '#8c1c1c',
  'suppressed-fg': '#7a7a7a',
  'old-value-fg': '#8a8a8a',
  'old-value-decoration': 'line-through',
  'seg-added-bg': '#a5d6a7',
  'seg-removed-bg': '#ef9a9a',
  'focus-outline': '2px solid #1976d2',
};

export const DARK_VARIABLES: Readonly<Record<string, string>> = {
  'border-color': '#3a3f45',
  'header-bg': '#1d2125',
  'body-bg': '#15181b',
  'body-fg': '#e6e6e6',
  'added-bg': '#12301a',
  'added-fg': '#8ddc9c',
  'deleted-bg': '#3a1618',
  'deleted-fg': '#f2a2a2',
  'modified-bg': '#33290d',
  'modified-fg': '#e8c96a',
  'moved-bg': '#1b2533',
  'finding-bg': '#3a1618',
  'finding-fg': '#f2a2a2',
  'suppressed-fg': '#9aa0a6',
  'old-value-fg': '#9aa0a6',
  'seg-added-bg': '#2c6b3a',
  'seg-removed-bg': '#7a2f33',
  'focus-outline': '2px solid #82b1ff',
};

/**
 * High contrast is not "dark with more saturation". It drops the background fills
 * entirely and carries change kind on a border and on the marker glyph, because a
 * user who needs this mode is usually the user for whom a pale fill conveys
 * nothing at all.
 */
export const HIGH_CONTRAST_VARIABLES: Readonly<Record<string, string>> = {
  'border-color': '#000000',
  'header-bg': '#ffffff',
  'body-bg': '#ffffff',
  'body-fg': '#000000',
  'added-bg': 'transparent',
  'added-fg': '#000000',
  'deleted-bg': 'transparent',
  'deleted-fg': '#000000',
  'modified-bg': 'transparent',
  'modified-fg': '#000000',
  'moved-bg': 'transparent',
  'finding-bg': 'transparent',
  'finding-fg': '#000000',
  'suppressed-fg': '#000000',
  'old-value-fg': '#000000',
  'old-value-decoration': 'line-through',
  'seg-added-bg': '#ffff00',
  'seg-removed-bg': '#ffffff',
  'focus-outline': '3px solid #000000',
};

function block(selector: string, decls: Readonly<Record<string, string>>): string {
  const body = Object.entries(decls)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');
  return `${selector} {\n${body}\n}`;
}

function vars(v: Readonly<Record<string, string>>, varPrefix: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, value] of Object.entries(v)) out[`--${varPrefix}-${k}`] = value;
  return out;
}

/** One theme file: variables only, no structure, as spec 8.3 requires of them. */
export function themeStylesheet(
  which: 'light' | 'dark' | 'high-contrast',
  prefix: string = DEFAULT_CLASS_PREFIX,
): string {
  assertClassPrefix(prefix);
  const p = prefix.replace(/-$/, '');
  const table = {
    light: LIGHT_VARIABLES,
    dark: DARK_VARIABLES,
    'high-contrast': HIGH_CONTRAST_VARIABLES,
  }[which];
  return [
    `/* @ibhatech/csvdiff-view: ${which} theme. Variables only; import the base`,
    `   stylesheet for structure. Generated from stylesheet.ts. */`,
    block(':root', vars(table, p)),
    '',
  ].join('\n');
}

/* eslint-disable max-lines-per-function -- one template, kept in one place */
export function defaultStylesheet(options: StylesheetOptions = {}): string {
  const prefix = options.prefix ?? DEFAULT_CLASS_PREFIX;
  assertClassPrefix(prefix);
  const c = (suffix: string) => `.${prefix}${suffix}`;
  const p = prefix.replace(/-$/, '');
  const v = (name: string) => `var(--${p}-${name})`;

  const head =
    options.variables === false
      ? ''
      : `${block(':root', vars(LIGHT_VARIABLES, p))}\n\n` +
        `@media (prefers-color-scheme: dark) {\n` +
        `  ${block(':root', vars(DARK_VARIABLES, p)).replace(/\n/g, '\n  ')}\n}\n\n`;

  return `/* @ibhatech/csvdiff-view default stylesheet, prefix "${prefix}".
   Generated from src/stylesheet.ts; edit that, not this.

   Styles both the HTML emitter's saved reports and the virtualized view. Every
   selector qualified by a data- attribute belongs to one of the two; everything
   else applies to both. */

${head}${c('report')} {
  color: ${v('body-fg')};
  background: ${v('body-bg')};
  font-family: ${v('font-family')};
  font-size: ${v('font-size')};
}

/* The virtualized view is a single scroll container on both axes, which is what
   keeps the sticky header from desynchronizing on a fast scroll. A saved report
   is a document and scrolls with the page, so it is left alone. */
${c('report')}[data-virtualized] {
  position: relative;
  overflow: auto;
  max-height: 100%;
  contain: paint;
}

${c('table')} {
  border-collapse: collapse;
  border-spacing: 0;
  width: max-content;
  min-width: 100%;
  table-layout: fixed;
}

${c('th')} {
  position: sticky;
  top: 0;
  z-index: 2;
  text-align: left;
  font-weight: 600;
  white-space: nowrap;
  padding: 0 ${v('cell-padding-x')};
  height: ${v('row-height')};
  background: ${v('header-bg')};
  border-bottom: 1px solid ${v('border-color')};
}

/* A column the schema declares as part of the key stays put horizontally, so the
   row is still identifiable when a wide file is scrolled to column 40. The view
   marks these; the emitter does not, and a saved report has nothing to scroll. */
${c('th')}[data-key="true"],
${c('cell')}[data-key="true"] {
  position: sticky;
  left: var(--${p}-key-left, 0);
  z-index: 1;
  background: inherit;
}
${c('th')}[data-key="true"] { z-index: 3; }

${c('num')} {
  width: 6ch;
  text-align: right;
  font-family: ${v('font-mono')};
  color: ${v('suppressed-fg')};
  padding: 0 ${v('cell-padding-x')};
  white-space: nowrap;
  user-select: none;
}

${c('mark')} {
  width: 2ch;
  text-align: center;
  font-family: ${v('font-mono')};
  padding: 0;
  user-select: none;
}

${c('row')} {
  height: ${v('row-height')};
  background: ${v('body-bg')};
}

${c('cell')} {
  padding: 0 ${v('cell-padding-x')};
  border-bottom: 1px solid ${v('border-color')};
  vertical-align: top;
  /* The emitter writes a cell's newline through unchanged rather than inventing a
     <br>. This is where that decision is made visible. */
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}

/* Stated rather than left to the default. A row can be unchanged and still be
   moved, or carry a finding, and both of those need something to sit on. */
${c('unchanged')} { background: ${v('body-bg')}; }
${c('modified')} { background: ${v('modified-bg')}; color: ${v('modified-fg')}; }
${c('added')}    { background: ${v('added-bg')};    color: ${v('added-fg')}; }
${c('deleted')}  { background: ${v('deleted-bg')};  color: ${v('deleted-fg')}; }
${c('row')}${c('moved')} { box-shadow: inset 3px 0 0 0 ${v('moved-bg')}; }

${c('cell')}${c('changed')} { font-weight: 600; }
${c('cell')}${c('suppressed')} { color: ${v('suppressed-fg')}; font-style: italic; }
${c('cell')}${c('finding')} {
  background: ${v('finding-bg')};
  color: ${v('finding-fg')};
  outline: 1px dashed currentColor;
  outline-offset: -1px;
}

${c('old')} {
  display: block;
  color: ${v('old-value-fg')};
  text-decoration: ${v('old-value-decoration')};
  font-weight: 400;
}
${c('new')} { display: block; }

${c('del')} { background: ${v('seg-removed-bg')}; text-decoration: inherit; }
${c('ins')} { background: ${v('seg-added-bg')}; text-decoration: none; }

/* Colour is never the only signal, per spec 8.5. The view renders a real marker
   cell; an emitter document has no such element, so it gets the same glyph from
   generated content. The two selectors are mutually exclusive. */
${c('report')}:not([data-virtualized]) ${c('row')}${c('modified')} > ${c('num')}::after { content: " ~"; }
${c('report')}:not([data-virtualized]) ${c('row')}${c('added')} > ${c('num')}::after    { content: " +"; }
${c('report')}:not([data-virtualized]) ${c('row')}${c('deleted')} > ${c('num')}::after  { content: " -"; }
${c('report')}:not([data-virtualized]) ${c('row')}${c('moved')} > ${c('num')}::before   { content: "\\21C5 "; }

/* Row presentation modes, spec 8.4. The DOM order of the two value spans is
   always old then new, matching the emitter, so a copy or a screen reader gets
   the same reading of both documents; where the old value sits visually is a
   presentation decision and is made here. */
${c('report')}[data-old-value-position="below"] ${c('cell')}${c('changed')} {
  display: flex;
  flex-direction: column-reverse;
}
${c('report')}[data-old-value-position="tooltip"] ${c('old')} {
  position: absolute;
  width: 1px;
  height: 1px;
  overflow: hidden;
  clip-path: inset(50%);
}

/* stacked: the lower physical row carries the old values and renders unchanged
   cells blank, so the eye goes straight to what differs. */
${c('row')}[data-variant="old"] ${c('cell')} {
  border-bottom-style: none;
  color: ${v('old-value-fg')};
  text-decoration: ${v('old-value-decoration')};
  font-weight: 400;
}
${c('row')}[data-variant="new"] ${c('cell')} { border-bottom-style: none; }

/* sideBySide: two panes in the one scroll container, so the vertical alignment is
   the browser's problem rather than a scroll event handler's. */
${c('report')}[data-layout="sideBySide"] {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 0;
}
${c('pane')} { min-width: 0; overflow: visible; }
${c('pane')} + ${c('pane')} { border-left: 2px solid ${v('border-color')}; }
${c('row')}[data-variant="gap"] ${c('cell')},
${c('row')}[data-variant="gap"] ${c('num')} {
  background: repeating-linear-gradient(
    135deg, transparent, transparent 6px, ${v('border-color')} 6px, ${v('border-color')} 7px
  );
}

/* The spacer rows a virtualized table uses to hold the scrollbar honest. They
   carry the height of everything not rendered, so the report scrolls as if all
   90,000 rows were present. */
${c('spacer')} { padding: 0; border: 0; }

${c('cell')}:focus-visible,
${c('row')}:focus-visible {
  outline: ${v('focus-outline')};
  outline-offset: -2px;
}

@media print {
  ${c('report')}[data-virtualized] { overflow: visible; max-height: none; }
  ${c('th')} { position: static; }
}
`;
}
