#!/usr/bin/env python3
"""Generate golden XXH3-64 test vectors for core/tests/xxh3_vectors.h.

The engine implements the one shot, unseeded, default secret subset of XXH3.
Bit exactness with upstream xxHash is a real requirement rather than a nicety:
the digest protocol in spec 2.5 has a server side computing row hashes, and a
hash that is merely "a good hash" would silently produce wrong diffs instead of
failing loudly.

So the expected values here come from the reference implementation itself, via
xxhsum, and the test regenerates the same byte patterns in C.

    python3 scripts-and-commands/gen_xxh3_vectors.py

Requires xxhsum on PATH (brew install xxhash).
"""
import pathlib
import shutil
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "core" / "tests" / "xxh3_vectors.h"

# Lengths chosen to cross every branch of the length dispatch: the 1-3, 4-8,
# 9-16, 17-128, 129-240 and >240 paths, each at its boundaries, plus sizes that
# exercise the long path's block loop, its partial block and its overlapping
# final stripe.
LENGTHS = [
    0, 1, 2, 3, 4, 5, 7, 8, 9, 12, 15, 16, 17, 24, 31, 32, 33, 48, 63, 64, 65,
    96, 97, 127, 128, 129, 130, 160, 200, 239, 240, 241, 255, 256, 257, 512,
    1023, 1024, 1025, 2048, 4096, 8192, 16384, 65536,
]


def pattern(n: int) -> bytes:
    """Deterministic byte pattern the C test reproduces exactly."""
    return bytes(((i * 167 + 13) & 0xFF) for i in range(n))


def xxh3(data: bytes) -> int:
    proc = subprocess.run(["xxhsum", "-H3"], input=data, capture_output=True, check=True)
    token = proc.stdout.decode().split()[0]
    assert token.startswith("XXH3_"), token
    return int(token[len("XXH3_"):], 16)


def main() -> int:
    if not shutil.which("xxhsum"):
        print("error: xxhsum not found on PATH. brew install xxhash", file=sys.stderr)
        return 1

    lines = [
        "/*",
        " * xxh3_vectors.h - golden vectors from the reference xxHash implementation.",
        " *",
        " * Generated by scripts-and-commands/gen_xxh3_vectors.py using xxhsum -H3.",
        " * Do not edit by hand. The byte pattern is (i * 167 + 13) & 0xFF, which",
        " * tests/test_hash.c reproduces.",
        " */",
        "#ifndef IBHA_XXH3_VECTORS_H",
        "#define IBHA_XXH3_VECTORS_H",
        "",
        "typedef struct {",
        "    unsigned long len;",
        "    unsigned long long expect;",
        "} ibha_xxh3_vector;",
        "",
        "static const ibha_xxh3_vector k_xxh3_vectors[] = {",
    ]
    for n in LENGTHS:
        lines.append(f"    {{ {n}ul, 0x{xxh3(pattern(n)):016x}ull }},")
    lines += [
        "};",
        "",
        f"#define IBHA_XXH3_VECTOR_COUNT {len(LENGTHS)}",
        "",
        "#endif /* IBHA_XXH3_VECTORS_H */",
    ]

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} with {len(LENGTHS)} vectors")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
