#!/usr/bin/env python3
"""Run the whole Phase 6 verification gate and report what passed.

    python3 scripts-and-commands/run_phase6_checks.py
    python3 scripts-and-commands/run_phase6_checks.py --quick      # skip the 15 MB pair
    python3 scripts-and-commands/run_phase6_checks.py --java-only

The Phase 5 gate in full, then everything the Java binding adds:

  - **the JNI library builds warning free** against the same flag set the engine
    is held to, with the header generated by `javac -h` so that every native
    signature is checked by the C compiler against its Java declaration. That is
    what turns the classic hand written JNI failure, a signature that drifted and
    surfaces as an UnsatisfiedLinkError or a misread argument, into a build error;
  - the JUnit suite, which includes the **row contract test**: the binding's
    decoded rows against the JSONL emitter's own output on the p90 pair, field for
    field. This binding decodes cells out of the columnar arrays rather than
    asking the engine for each one, so the row contract has a third
    implementation, and a third implementation nothing compares against the first
    two is just a place for them to drift;
  - **the determinism check with Java as a fourth producer**, which is where spec
    section 9's actual promise is tested: a server side reconciliation and a
    browser preview of the same pair are the same report, byte for byte, or the
    preview is not a preview.

The Java steps are reported as skipped rather than failed when Maven is absent,
the way the pnpm steps are, because a gate that cannot run on a fresh checkout is
a gate nobody runs. `--require-java` refuses that and is what CI should pass.
"""
import argparse
import pathlib
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
JAVA = ROOT / "java"
SCRIPTS = ROOT / "scripts-and-commands"


def java_steps(quick: bool, require_java: bool):
    """(label, argv, cwd, required)."""
    have_mvn = shutil.which("mvn") is not None
    if require_java and not have_mvn:
        print("error: --require-java was given and mvn is not installed")
        raise SystemExit(2)

    determinism = ["node", str(SCRIPTS / "check_determinism.mjs")]
    if quick:
        determinism.append("--quick")
    if have_mvn or require_java:
        determinism.append("--require-java")

    return [
        # Compiles the engine and the glue into one shared library. Needs no Maven,
        # so it runs even where the rest is skipped: a warning in the JNI layer is
        # worth catching on any machine.
        ("jni library builds warning free",
         ["python3", str(SCRIPTS / "build_jni.py"), "--quiet"], ROOT, True),
        # Not -q: the quiet flag suppresses the very line worth reporting, which is
        # how many assertions actually ran.
        ("java binding suite, including the emitter row contract",
         ["mvn", "-B", "test"], JAVA, have_mvn),
        ("determinism, native against both wasm builds and java",
         determinism, ROOT, have_mvn),
    ]


def run(label: str, argv: list, cwd: pathlib.Path, required: bool) -> tuple:
    if not required:
        return ("skipped", label, "maven is not installed")
    try:
        proc = subprocess.run(argv, cwd=cwd, capture_output=True, text=True)
    except FileNotFoundError as err:
        return ("skipped", label, f"{err}")
    out = proc.stdout + proc.stderr
    if proc.returncode == 0:
        return ("ok", label, out)
    return ("FAILED", label, out)


def clean(line: str) -> str:
    """Maven prefixes every line with a level, and the interesting ones are the
    lines underneath it."""
    s = line.strip()
    for prefix in ("[INFO] ", "[ERROR] ", "[WARNING] "):
        if s.startswith(prefix):
            return s[len(prefix):]
    return s


def summarize(out: str) -> str:
    keep = []
    for line in out.splitlines():
        s = clean(line)
        if s.startswith("all ") and "identical" in s:
            keep.append(s)
        elif s.startswith("Tests run:") and "Time elapsed" not in s:
            keep.append(s)
        elif s.startswith("jni library:"):
            keep.append(s)
        elif s.startswith("FAILED") or s.startswith("FAIL ") or s.startswith("error:"):
            keep.append(s)
    return "; ".join(keep[:6])


def test_totals(out: str) -> str:
    """Surefire prints a per class line and one total; the total is the last."""
    lines = [clean(l) for l in out.splitlines() if clean(l).startswith("Tests run:")]
    return lines[-1] if lines else ""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true",
                    help="skip the 15 MB pair in the determinism check")
    ap.add_argument("--java-only", action="store_true",
                    help="skip the engine, the binding and the view")
    ap.add_argument("--require-java", action="store_true",
                    help="fail rather than skip when maven is absent")
    ap.add_argument("--fuzz-iters", type=int, default=200000)
    args = ap.parse_args()

    failures = 0

    if not args.java_only:
        print("== the engine, the binding and the view, Phases 0 to 5 ==", flush=True)
        argv = ["python3", str(SCRIPTS / "run_phase5_checks.py"),
                "--fuzz-iters", str(args.fuzz_iters)]
        if args.quick:
            argv.append("--quick")
        if subprocess.run(argv, cwd=ROOT).returncode != 0:
            failures += 1
        print()

    print("== the java binding, Phase 6 ==", flush=True)
    for label, argv, cwd, required in java_steps(args.quick, args.require_java):
        status, name, out = run(label, argv, cwd, required)
        if status == "FAILED":
            failures += 1
        print(f"[{status:>7}] {name}")
        detail = summarize(out)
        total = test_totals(out)
        if total and total not in detail:
            detail = f"{total}; {detail}" if detail else total
        if detail:
            print(f"           {detail}")
        if status == "FAILED":
            print("\n".join("           " + l for l in out.splitlines()[-30:]))

    print()
    print("gate failed" if failures else "gate passed")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
