/**
 * GENERATED FILE. Do not edit.
 *
 *   node scripts-and-commands/gen_abi.mjs
 *
 * The wasm32 byte layout of every public struct in core/include/ibha_csvdiff.h,
 * asked of the compiler that builds the module rather than written out by hand.
 * The list of fields lives in core/tools/abi_offsets.c; regenerating is checked
 * in the gate, so a struct cannot change without this file changing with it.
 *
 * Every offset here is a byte offset into wasm linear memory, and every pointer
 * field is 4 bytes wide because the target is wasm32. The binding asserts that
 * on load rather than assuming it.
 */

/** Width of a pointer on the target these offsets were taken for. */
export const POINTER_SIZE = 4;

/** Compile time constants from the header, so the binding never restates one. */
export const C = {
  VERSION_MAJOR: 0,
  VERSION_MINOR: 1,
  VERSION_PATCH: 0,
  SCHEMA_VERSION: 1,
  DEFAULT_MAX_BYTES: 157286400,
  DEFAULT_MAX_CELL_BYTES: 4096,
  NO_ROW: 4294967295,
  NO_COLUMN: 4294967295,
  HEADER_AUTO: 4294967295,
  HEADER_SCAN_ROWS: 8,
  TYPE_TEXT_MAX: 40,
  FIELD_QUOTED: 1,
  FIELD_HAS_ESCAPE: 2,
  FIELD_HAS_NEWLINE: 4,
  FIELD_EMPTY: 8,
  COL_KEY: 1,
  COL_REQUIRED: 2,
  CELL_CHANGED: 1,
  CELL_SUPPRESSED: 2,
  CELL_REQUIRED_EMPTY: 4,
  CELL_TOO_LONG: 8,
  CELL_NOT_NUMERIC: 16,
  CELL_PRECISION: 32,
  CELL_FINDING: 60,
} as const;

/** Byte offsets, sizes and alignments, keyed by struct then by field. */
export const OFF = {
  limits: {
    __size: 16,
    __align: 8,
    max_bytes: 0,
    max_rows: 8,
    max_columns: 12,
  },
  ingest_stats: {
    __size: 24,
    __align: 8,
    bytes: 0,
    line_breaks: 8,
    quotes: 16,
  },
  dialect: {
    __size: 3,
    __align: 1,
    delimiter: 0,
    quote: 1,
    strip_bom: 2,
  },
  header_opts: {
    __size: 20,
    __align: 4,
    rows: 0,
    key_row: 4,
    required_row: 8,
    type_row: 12,
    name_row: 16,
  },
  compare_opts: {
    __size: 36,
    __align: 4,
    trim_whitespace: 0,
    char_ignore_pad: 4,
    numeric: 8,
    booleans: 12,
    date_compare: 16,
    bool_true: 20,
    bool_false: 24,
    allow_added_columns: 28,
    allow_removed_columns: 32,
  },
  parse_opts: {
    __size: 88,
    __align: 8,
    dialect: 0,
    header: 4,
    compare: 24,
    expect_table: 60,
    expect_schema: 64,
    size_hint: 72,
    hash_rows: 80,
  },
  parse_stats: {
    __size: 40,
    __align: 8,
    bytes: 0,
    n_rows: 8,
    n_fields: 12,
    n_columns: 16,
    quoted_fields: 20,
    escaped_fields: 24,
    multiline_fields: 28,
    ragged_normalized: 32,
    blank_lines: 36,
  },
  table: {
    __size: 72,
    __align: 8,
    bytes: 0,
    len: 4,
    field_off: 8,
    field_len: 12,
    field_flags: 16,
    n_fields: 20,
    row_first_field: 24,
    n_rows: 28,
    row_key_hash: 32,
    row_full_hash: 36,
    row_raw_hash: 40,
    n_columns: 44,
    quote: 48,
    compare_id: 56,
    has_digests: 64,
  },
  schema: {
    __size: 48,
    __align: 4,
    n_columns: 0,
    n_key_columns: 4,
    col_flags: 8,
    col_type: 12,
    col_size: 16,
    col_scale: 20,
    key_row: 24,
    required_row: 28,
    type_row: 32,
    name_row: 36,
    first_data_row: 40,
    names_only: 44,
  },
  diff_opts: {
    __size: 80,
    __align: 8,
    compare: 0,
    detect_moves: 36,
    source_ordered: 40,
    count_suppressed: 44,
    validate: 48,
    require_key: 52,
    deleted_placement: 56,
    similarity_k: 60,
    similarity_percent: 64,
    max_pair_work: 72,
  },
  row: {
    __size: 36,
    __align: 4,
    kind: 0,
    moved: 1,
    move_distance: 4,
    source_row: 8,
    target_row: 12,
    n_columns: 16,
    n_changed_cells: 20,
    n_suppressed_cells: 24,
    n_findings: 28,
    cell_flags: 32,
  },
  diff_stats: {
    __size: 104,
    __align: 8,
    rows_unchanged: 0,
    rows_modified: 4,
    rows_added: 8,
    rows_deleted: 12,
    rows_moved: 16,
    report_rows: 20,
    cells_changed: 24,
    cells_suppressed: 32,
    cells_required_empty: 40,
    cells_too_long: 48,
    cells_not_numeric: 56,
    cells_bad_precision: 64,
    rows_with_findings: 72,
    columns_added: 76,
    columns_removed: 80,
    n_columns_compared: 84,
    paired_by_similarity: 88,
    pairing_truncated: 92,
    all_keys: 96,
    moves_forced_off: 100,
  },
  segment: {
    __size: 12,
    __align: 4,
    op: 0,
    start: 4,
    len: 8,
  },
  emit_opts: {
    __size: 36,
    __align: 4,
    format: 0,
    changes_only: 4,
    include_values: 8,
    cell_diff: 12,
    max_cell_bytes: 16,
    max_rows: 20,
    csv_formula_guard: 24,
    csv_delimiter: 28,
    class_prefix: 32,
  },
  sink: {
    __size: 8,
    __align: 4,
    write: 0,
    ctx: 4,
  },
  buffer_sink: {
    __size: 16,
    __align: 4,
    bytes: 0,
    cap: 4,
    len: 8,
    overflow: 12,
  },
  buffer_reader: {
    __size: 12,
    __align: 4,
    bytes: 0,
    len: 4,
    pos: 8,
  },
} as const;

/** Number of entries the generator emitted, asserted by the ABI self check so
 *  that a truncated regeneration is loud rather than subtle. */
export const ABI_FIELD_COUNT = 185;
