/*
 * xxh3_vectors.h - golden vectors from the reference xxHash implementation.
 *
 * Generated by scripts-and-commands/gen_xxh3_vectors.py using xxhsum -H3.
 * Do not edit by hand. The byte pattern is (i * 167 + 13) & 0xFF, which
 * tests/test_hash.c reproduces.
 */
#ifndef IBHA_XXH3_VECTORS_H
#define IBHA_XXH3_VECTORS_H

typedef struct {
    unsigned long len;
    unsigned long long expect;
} ibha_xxh3_vector;

static const ibha_xxh3_vector k_xxh3_vectors[] = {
    { 0ul, 0x2d06800538d394c2ull },
    { 1ul, 0x8a21d78b1538b1c0ull },
    { 2ul, 0xa020a917c68e5888ull },
    { 3ul, 0x5f1fa6d2a3aa5a3bull },
    { 4ul, 0xa8a9b82c81542a43ull },
    { 5ul, 0x2f1e508dc78686c2ull },
    { 7ul, 0x1a5de7fedcc8d90dull },
    { 8ul, 0x67b8f67a80d308a6ull },
    { 9ul, 0x7df166798fe37670ull },
    { 12ul, 0x2ee9684733877373ull },
    { 15ul, 0x1bc6c65a03a87951ull },
    { 16ul, 0xc0967fee676a5837ull },
    { 17ul, 0xbc307578d06e9d93ull },
    { 24ul, 0x2ca64240aaa3e38full },
    { 31ul, 0x2d2ee27366193cf5ull },
    { 32ul, 0xffdae7523dd0daecull },
    { 33ul, 0x27b514591ef37d2dull },
    { 48ul, 0x091d71413400e75aull },
    { 63ul, 0xdd8efa4b1b30adb3ull },
    { 64ul, 0x2c6e0b294abfc3f0ull },
    { 65ul, 0x31d8db1918167d5cull },
    { 96ul, 0x1ebab520f4c1e5afull },
    { 97ul, 0x4a2cfee5178bde3cull },
    { 127ul, 0x1373662ceb8090a9ull },
    { 128ul, 0xa45617bfe9bb88d6ull },
    { 129ul, 0x4ca31f6b2cfd9a3eull },
    { 130ul, 0x7858bf7d4569bf51ull },
    { 160ul, 0x2fb4144dd1b5a99eull },
    { 200ul, 0x96c004e238c9b788ull },
    { 239ul, 0x445e8238d8be5de5ull },
    { 240ul, 0x2817ed3cdf9547e7ull },
    { 241ul, 0x02f838dd48200ee8ull },
    { 255ul, 0xd084c9edabd7749cull },
    { 256ul, 0xc67d143ec3572269ull },
    { 257ul, 0xac756e3b633ed5baull },
    { 512ul, 0x81d2bb89df27623eull },
    { 1023ul, 0x470376f374f704ccull },
    { 1024ul, 0x4ecde09865c37511ull },
    { 1025ul, 0xa08b2694bf52957eull },
    { 2048ul, 0x1d0f40a0ff717f3eull },
    { 4096ul, 0x5b1812436f21d06dull },
    { 8192ul, 0x2d0bd4c68273e5b3ull },
    { 16384ul, 0x17a9df4223fcb588ull },
    { 65536ul, 0x08b3656a49fda734ull },
};

#define IBHA_XXH3_VECTOR_COUNT 44

#endif /* IBHA_XXH3_VECTORS_H */
